import React from 'react'
import Head from "next/head";
import styles from '../modules/layout.module.css'
import { useRouter } from 'next/router';
import Navbar from './Navbar';
import { UpBar } from './UpBar';

const Layout = ({children}) => {
  const router = useRouter();

  // creamos una lista de las rutas donde NO quiero que aparezca el navbar
  const noNavbarRoutes = ['/', '/ResumenAVencer', '/ResumenVencido'];

  // verificamos si la ruta actual esta dentro de la lista de rutas condicionadas
  const hideNavbar = noNavbarRoutes.includes(router.pathname);

  return (
    <>
    <Head>
        <title>Cobranzas Basani</title>
        <meta name="description" content="Generated by Bernardo Broscheit" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
    </Head>
    <main className={styles.container}>
        {!hideNavbar && <Navbar/>}
        {/* <Navbar /> */}
        <div>
            {!hideNavbar && <UpBar />}
            {/* <UpBar /> */}
            <div>{children}</div>
        </div>
    </main>
    </>
  )
}

export default Layout